import {
  SiJavascript,
  SiNodedotjs,
  SiPython,
  SiSharp,
  SiPhp,
  SiGo,
  SiRuby,
  SiSwift,
  SiCurl,
  SiGetx,
  SiJquery,
  SiAxios,
} from 'react-icons/si';

export const LANG_ICONS: Record<string, React.ElementType> = {
  curl: SiCurl,
  httpie: SiCurl,
  wget: SiGetx,
  fetch: SiJavascript,
  axios: SiAxios,
  jquery: SiJquery,
  xhr: SiJavascript,
  node_native: SiNodedotjs,
  node_request: SiNodedotjs,
  node_unirest: SiNodedotjs,
  python: SiPython,
  java_okhttp: SiJavascript,
  java_unirest: SiJavascript,
  csharp_httpclient: SiSharp,
  csharp_restsharp: SiSharp,
  go: SiGo,
  php_curl: SiPhp,
  php_guzzle: SiPhp,
  ruby: SiRuby,
  swift: SiSwift,
};
