name: Create Branch from Trello

on:
  repository_dispatch:
    types: [trello-create-branch]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create branch from card
      run: |
        # Создаем имя ветки из названия карточки
        BRANCH_NAME="${{ github.event.client_payload.branch_name }}"
        # Очищаем имя от спецсимволов
        CLEAN_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/-\+/-/g')
        
        # Создаем ветку
        git checkout -b "$CLEAN_BRANCH_NAME"
        git push origin "$CLEAN_BRANCH_NAME"
        
        echo "Branch created: $CLEAN_BRANCH_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.TRELLO_GITHUB_TOKEN }}
